### ISSUE TITLE
Please Update!

### ISSUE THREAD

**Issue by ghost** [superhawk610/rn-detect-soft-nav#2]
Could you please update all gradle build dependencies etc. and check in general if everything is still working cause your package is the only one I could find which provides this functionality (correct me if I am wrong). I get a lot of Warnings that something is outdated so yeah
Thx a lot

**Comment by superhawk610** [comment]
@zepfgeorg I've got a few projects ongoing at the moment, but I'll try and take a look soon. The next major RN release (with the new Hooks API) should be coming in the next couple of weeks so I'll try to have this updated by then. If you want to get it fixed up for now, you should be able to fork this repo and update the dependency versions, then just install with

```
npm install -S https://github.com/zepfgeorg/rn-detect-soft-nav
```

**Comment by ghost** [comment]
@superhawk610 
Thx I appreciate your support

**Comment by zepfgeorg** [comment]
@superhawk610 I got it working but now I have the same issue as already mentioned. DetectSoftNav.isVisible() always gives true. How can I fix it because I can not work with the relevant native portion of the code as in #1. Thx
