### ISSUE TITLE
.isVisible always true

### ISSUE THREAD

**Issue by ghost** [superhawk610/rn-detect-soft-nav#3]
I got #2 working but now I have the same issue as already mentioned. DetectSoftNav.isVisible() always gives true. How can I fix it because I can not work with the relevant native portion of the code as in #1. Thx

**Comment by ghost** [comment]
I debuggt a bit and noticed that the .getWindow throws an warning:

Method invocation 'getWindow' may produce 'java.lang.NullPointerException' less... (Strg+F1) 
Inspection info: <strong>This inspection analyzes method control and data flow to report possible conditions that are always true or false,</strong> expressions whose value is statically proven to be constant, and situations that can lead to nullability contract violations.

**Comment by superhawk610** [comment]
According to [the](https://developer.android.com/training/system-ui/immersive) [spec](https://developer.android.com/training/system-ui/visibility) that function should be working, but if you dig around for a bit you'll note that there is almost no documentation written for this API and no discussion around it either, which makes debugging very difficult. My background is largely in JS, I'm mostly just hacking around with native Android Java code.

A workaround you can use is to keep track of the soft nav state in your JS code using an instance or state variable and then toggle it accordingly in `softNavDidShow` and `softNavDidHide`.

**Comment by ghost** [comment]
I need to get the bool at componentDidMount. But the event listener only fires if I toggle the softNav. Is there a way I can trigger the event listener

**Comment by superhawk610** [comment]
Right, until `.isVisible` is working it's not possible to do correctly.

The only thing I can think to try is making the following change [here](https://github.com/superhawk610/rn-detect-soft-nav/blob/master/android/src/main/java/pro/aaronross/util/detectsoftnav/DetectSoftNavModule.java#L55):

```diff
-         View decorView = getCurrentActivity().getWindow().getDecorView().getRootView();
+         View decorView = getCurrentActivity().getWindow().getDecorView();
```

but like I said this was for a project that has since been abandoned so I may not be able to get it working in a reasonable amount of time (or ever). Sorry 😬

**Comment by ghost** [comment]
Thx so much for your help

**Comment by ghost** [comment]
But sadly still nothing

**Comment by superhawk610** [comment]
If I ever do get around to debugging and fixing this, I'll update this thread. Good luck!

**Comment by ghost** [comment]
Thx
